{"name": "test_check_successful_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestAuthentication' object has no attribute 'login_facade'. Did you mean: 'login_page'?", "trace": "self = <auth2_test.TestAuthentication object at 0x10d14ef80>\n\n    def test_check_successful_login(self):\n>       self.login_facade.open_login_form()\nE       AttributeError: 'TestAuthentication' object has no attribute 'login_facade'. Did you mean: 'login_page'?\n\nauth2_test.py:34: AttributeError"}, "start": 1685973427379, "stop": 1685973427380, "uuid": "7b53f5b3-9a5c-44fd-ab5f-001ff5785fdf", "historyId": "7b13529f5f14072763bbe91d42d3a1db", "testCaseId": "7b13529f5f14072763bbe91d42d3a1db", "fullName": "auth2_test.TestAuthentication#test_check_successful_login", "labels": [{"name": "suite", "value": "auth2_test"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "Yanas-MacBook-Pro.local"}, {"name": "thread", "value": "1769-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "auth2_test"}]}